ctripcorp/flybirds

- docs/demoproject.md
- docs/demoproject_zhCN.md
- docs/flybirds_cli.md
- docs/flybirds_cli_zhCN.md
> docs: update  docs

- flybirds/core/config_manage.py
- flybirds/core/launch_cycle/run_manage.py
- flybirds/core/plugin/loader.py
- flybirds/report/parallel_runner.py
> fix: handle Uppercase and lowercase

- docs/demoproject.md
- docs/demoproject_zhCN.md
- flybirds/template/pscript/custom_handle/operation.py
add comments to custom create_browser_context()
> Feat web new

- flybirds/core/config_manage.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/script_config.py
> fix compatible

- flybirds/report/fail_feature_create.py
> fix rerun miss feature tags

- flybirds/core/dsl/hook/control_hook.py
- flybirds/core/plugin/event/feature.py
change remove cache event step
> change remove cache event step

- flybirds/core/plugin/plugins/default/screen.py
> add background step to screen

- flybirds/core/plugin/event/step.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/template/pscript/custom_handle/operation.py
- flybirds/utils/dsl_helper.py
add step cache and web console
> add step cache and web console

- flybirds/cli/__main__.py
remove rerun default value 'true'
> remove rerun default value 'true'

- flybirds/core/config_manage.py
- flybirds/core/global_resource.py
- flybirds/core/plugin/event/web_run.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/screen_record.py
- flybirds/utils/launch_helper.py
> add browserExitAfterCase

- flybirds/core/config_manage.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/ui_driver.py
- flybirds/template/config/flybirds_config.json
"emulatedDevice": "iPad (gen 6)",
"userAgent": "My user agent",
"width": 550,
"height": 550,
"locale": "de-DE",
"timezone": "Europe/Berlin",
"deviceScaleFactor": 6,
"hasTouch": false,
"geolocation": {
"longitude": 48.858455,
"latitude": 2.294474
},
"permissions": ["geolocation"]
> Web more config

- flybirds/core/plugin/event/scenario.py
- flybirds/template/pscript/dsl/hook.py
> Main scenario event

- flybirds/report/json_format_deal.py
> fix json format with ignore case

- flybirds/core/plugin/plugins/default/ui_driver/poco/poco_swipe.py
> fix over ele swipe

- flybirds/core/config_manage.py
- flybirds/core/plugin/plugins/default/web/ui_driver.py
"proxy": "10.2.21.146:8080",
"bypass": ".tset.com,.bb.cn."
> add proxy browser config

- flybirds/core/plugin/plugins/default/screen_record.py
- flybirds/report/json_format_deal.py
fix report step and add record clear
> fix report step and add record clear

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/page.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/step.py
- requirements.txt
Add 4 DSL
1. add cookie
2. get cookie
3. get local storage
4. get session storage
> 155 web support add cookies and view cookies dsl

- flybirds/core/config_manage.py
- flybirds/core/plugin/event/scenario.py
- flybirds/core/plugin/plugins/default/screen_record.py
- flybirds/template/config/flybirds_config.json
fix copy record for airtest high version which is higher than 1.2.9
> Fix copy record

- flybirds/core/global_resource.py
- flybirds/core/plugin/loader.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/utils/pkg_helper.py
> add web context hook

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/element.py
- flybirds/core/plugin/plugins/default/web/element.py
- flybirds/core/plugin/plugins/default/web/step.py
> add web touch

- flybirds/core/plugin/plugins/default/web/page.py
> Main add new page hook

- flybirds/core/plugin/plugins/default/web/page.py
fix operation and add user define func
> fix operation and add user define func

- flybirds/core/plugin/plugins/default/web/page.py
> change  get_operation

- flybirds/core/plugin/plugins/default/web/page.py
> Main page add init params

- flybirds/utils/dsl_helper.py
> Main add jquery path

- flybirds/utils/dsl_helper.py
> support jquery path

- flybirds/utils/file_helper.py
> Main fix casename

- flybirds/utils/verify_helper.py
> fix: null verify

- flybirds/core/plugin/plugins/default/web/page.py
> ref add step cookie glob

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/request.py
- flybirds/core/plugin/event/web_run.py
- flybirds/core/plugin/plugins/default/web/interception.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/step.py
- flybirds/utils/file_helper.py
feat: mock by request body jpath
> feat: mock by request body jpath

- flybirds/utils/verify_helper.py
> fix: replace &nbsp to space

- flybirds/core/dsl/step/element.py
- flybirds/core/dsl/step/page.py
- flybirds/core/dsl/step/request.py
- flybirds/utils/dsl_helper.py
feat: add verify count on step
> feat: add verify count on step

- flybirds/core/dsl/step/step_loader.py
> Main feat add behave word

- flybirds/core/plugin/event/web_run.py
> Main fix close error

- flybirds/core/plugin/plugins/default/web/page.py
> Main fix mock fetch

- flybirds/core/plugin/plugins/default/ui_driver/poco/poco_manage.py
ref: find poco ele has text default
> ref: find poco ele has text default

- flybirds/core/plugin/event/config.py
- flybirds/utils/dsl_helper.py
- flybirds/utils/flybirds_log.py
> feat: add debug

- flybirds/core/plugin/plugins/default/web/page.py
> ref: change default to json

- flybirds/core/plugin/plugins/default/web/page.py
> ref: remove log

- flybirds/core/plugin/plugins/default/web/page.py
> Main fix playwright bypass

- flybirds/core/plugin/plugins/default/web/page.py
change json body with application-json
> change json body with application-json

- flybirds/core/dsl/step/common.py
> Main add ele wrap

- flybirds/core/plugin/plugins/default/web/page.py
> Main ref debug

- flybirds/utils/file_helper.py
> add file log

- flybirds/core/global_resource.py
- flybirds/core/plugin/plugins/default/web/interception.py
> add mock base path

- flybirds/core/plugin/plugins/default/web/page.py
> add http status

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/request.py
- flybirds/core/plugin/plugins/default/web/interception.py
- flybirds/core/plugin/plugins/default/web/step.py
页面请求了接口[{service}]
等待接口[{service}]请求结束
> Main yls retry

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/element.py
- flybirds/core/plugin/plugins/default/web/element.py
- flybirds/core/plugin/plugins/default/web/step.py
1. page contain text step added
> Main feat add new step

- flybirds/cli/parse_args.py
- flybirds/core/dsl/step/element.py
- flybirds/core/dsl/step/page.py
- flybirds/core/dsl/step/request.py
- flybirds/core/exceptions.py
- flybirds/core/plugin/event/driver_func_hook.py
- flybirds/core/plugin/event/scenario.py
- flybirds/core/plugin/event/step.py
- flybirds/core/plugin/plugins/default/web/element.py
- flybirds/core/plugin/plugins/default/web/interception.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/step.py
- flybirds/utils/dsl_helper.py
- flybirds/utils/verify_helper.py
> Main ref more exception

- flybirds/core/dsl/hook/control_hook.py
- flybirds/core/global_context.py
- flybirds/core/plugin/event/run.py
- flybirds/core/plugin/event/scenario.py
- flybirds/core/plugin/event/user_event.py
- flybirds/core/plugin/plugins/default/app_base_step.py
> split run event

- flybirds/core/plugin/event/screen_record_init.py
> Main fix miss record

- flybirds/core/exceptions.py
> fix error type

- flybirds/core/plugin/event/scenario.py
> Main fix stop record

- flybirds/core/dsl/globalization/i18n.py
- flybirds/core/dsl/step/element.py
- flybirds/core/exceptions.py
- flybirds/core/plugin/event/scenario.py
- flybirds/core/plugin/plugins/default/web/element.py
- flybirds/core/plugin/plugins/default/web/page.py
- flybirds/core/plugin/plugins/default/web/step.py
> add dialog

- flybirds/core/plugin/plugins/default/web/page.py
> change from context to page

- flybirds/core/plugin/plugins/default/web/page.py
> Main feat steam mock

- flybirds/core/config_manage.py
- flybirds/core/global_resource.py
- flybirds/core/plugin/event/tag.py
- flybirds/core/use_external/config.py
> Main feat eleconfig

- flybirds/core/plugin/event/scenario.py
- flybirds/core/plugin/plugins/default/web/page.py
> record response

- flybirds/core/exceptions.py
>  fix mulit ele error

- flybirds/core/exceptions.py
> fix error unk

- flybirds/core/exceptions.py
- flybirds/core/plugin/plugins/default/ui_driver/poco/poco_ele.py
- flybirds/core/plugin/plugins/default/ui_driver/poco/poco_findsnap.py
- flybirds/core/plugin/plugins/default/ui_driver/poco/poco_input.py
> feat app error

- flybirds/core/plugin/plugins/default/web/page.py
> fix add default value

- flybirds/core/plugin/plugins/default/web/page.py
> ref remove console log
